chore: reduce noise by task to check link validity
Unfortunately, Lychee will always print out something, even it all links
are valid. Because all other checks can be silent, some scripting has
been added to the task to behave uniform and reduce the noise. When
running `task check` is exits silently if no tool detected an issue.

diff --git a/Taskfile.yml b/Taskfile.yml
--- a/Taskfile.yml
+++ b/Taskfile.yml
@@ -117,7 +117,15 @@ tasks:
   check:link-validity:
     desc: check if external and internal links are still working (supports list of files as argument)
     deps: [setup:development-environment]
-    cmd: lychee --no-progress {{ .CLI_ARGS | default .ROOT_DIR }}
+    # Make Lychee silent if all links are valid to avoid noise.
+    cmd: |
+      output="$(lychee --no-progress {{ .CLI_ARGS | default .ROOT_DIR }})" || true
+
+      # Can't use exit code of Lychee, because Task doesn't allow noerrexit option
+      if grep --quiet "Issues found" <<< "$output"; then
+        echo $output
+        exit 1
+      fi
 
   verify:staged-changes:
     desc: verify list of staged files including automated fixes to be staged (requires list of staged files as argument)
